version: 0.2
phases:
  pre-build:
    commands:
      - echo "Entered a pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:explore
  post-build:
    commands:
      - echo "Enter post build state"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*