version: 0.2
phases:
  pre_build:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Entered a pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:explore
  post_build:
    commands:
      - echo "Enter post build state"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
